name: Terraform JDN AZDO Provider

trigger:
  branches:
    include:
    - '*'
pool:
  name: Kubernetes Cluster

steps:
    - script: |
        git config user.name "Gittyhub"
        git clone ssh://tfs.app.jandenul.com:22/tfs/DefaultCollection/Kubernetes/_git/terraform-provider-jdn-azdo-src MyRepo
        cd MyRepo
        git remote remove github
        echo https://$(GH_PAT)@github.com/JdnDevops/terraform-provider-azdo.git
        git remote add github https://$(GH_PAT)@github.com/JdnDevops/terraform-provider-azdo.git
        git pull origin main --rebase
        git reset --hard origin/main
        git push -u github main --force --tags
      displayName: 'Copy Code to GitHub'
